### ISSUE TITLE
Moin Ahmed Zahir - mzahi001

### ISSUE THREAD

**Issue by MAZ275-code** [odu-cs625-datavis/public-Fall24-aveerasa-Public#3]

**Comment by NAVYAOGIRALA** [comment]
Please follow the given instructions and submit your correct GitHub user name for GitHub repo creation.

**Comment by NAVYAOGIRALA** [comment]
Repo created: https://github.com/odu-cs625-datavis/Fall24-aveerasa-MAZ275-code
